package com.Hospital.UIClasses;

import com.Hospital.SearchingAndModiciation.ModifyEntities;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;

public class LoginScreen extends javax.swing.JFrame {
    public ModifyEntities modificationFunctions=new ModifyEntities();

    public LoginScreen() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("UIComponents\\hos.png");
        this.setIconImage(icon);
        this.setTitle("Lahore General Hospital IMS");
        this.setLocationRelativeTo(null);
        jPanel6.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userName = new javax.swing.JTextField();
        userPassword = new javax.swing.JPasswordField();
        forgotePassword = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel_SoftZyd = new javax.swing.JLabel();
        jLabel_inven = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        resetUserName = new javax.swing.JTextField();
        restUserPhone = new javax.swing.JTextField();
        resetUserNewPassword = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userName.setBackground(new java.awt.Color(31, 36, 42));
        userName.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        userName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                userNameMouseMoved(evt);
            }
        });
        jPanel1.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 205, 260, 40));

        userPassword.setBackground(new java.awt.Color(31, 36, 42));
        userPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 17)); // NOI18N
        userPassword.setForeground(new java.awt.Color(255, 255, 255));
        userPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        jPanel1.add(userPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 305, 260, 40));

        forgotePassword.setBackground(new java.awt.Color(169, 224, 49));
        forgotePassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        forgotePassword.setForeground(new java.awt.Color(169, 224, 49));
        forgotePassword.setText("Forgote password?");
        forgotePassword.setBorder(null);
        forgotePassword.setBorderPainted(false);
        forgotePassword.setContentAreaFilled(false);
        forgotePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotePassword.setRequestFocusEnabled(false);
        forgotePassword.setVerifyInputWhenFocusTarget(false);
        forgotePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotePasswordActionPerformed(evt);
            }
        });
        jPanel1.add(forgotePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_User_Shield_100px.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Facebook_32px_2.png")); // NOI18N
        jButton3.setToolTipText("Facebook");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Facebook_32px_7.png")); // NOI18N
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 28));

        jButton5.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Secured_Letter_32px.png")); // NOI18N
        jButton5.setToolTipText("Email");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Secured_Letter_32px_2.png")); // NOI18N
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 28));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Lock_35px.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 45));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Male_User_35px.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 45));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(169, 224, 49));
        jLabel19.setText("User Name");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 172, 150, 0));

        jPanel3.setBackground(new java.awt.Color(31, 36, 42));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Cancel_32px.png")); // NOI18N
        jButton10.setToolTipText("Close");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Cancel_30px_3.png")); // NOI18N
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 40));

        jButton11.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Minus_32px_1.png")); // NOI18N
        jButton11.setToolTipText("Minimize");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setFocusPainted(false);
        jButton11.setRequestFocusEnabled(false);
        jButton11.setRolloverIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Minus_30px_3.png")); // NOI18N
        jButton11.setVerifyInputWhenFocusTarget(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 40, 40));

        jLabel_SoftZyd.setFont(new java.awt.Font("Trebuchet MS", 1, 27)); // NOI18N
        jLabel_SoftZyd.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_SoftZyd.setText("Lahore General Hospital");
        jPanel3.add(jLabel_SoftZyd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 314, -1));

        jLabel_inven.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel_inven.setForeground(new java.awt.Color(169, 224, 49));
        jLabel_inven.setText("Management System");
        jPanel3.add(jLabel_inven, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 250, 314, -1));

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetUserName.setBackground(new java.awt.Color(31, 36, 42));
        resetUserName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        resetUserName.setForeground(new java.awt.Color(255, 255, 255));
        resetUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        resetUserName.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                resetUserNameMouseMoved(evt);
            }
        });
        jPanel6.add(resetUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 160, 40));

        restUserPhone.setBackground(new java.awt.Color(31, 36, 42));
        restUserPhone.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        restUserPhone.setForeground(new java.awt.Color(255, 255, 255));
        restUserPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        restUserPhone.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                restUserPhoneMouseMoved(evt);
            }
        });
        jPanel6.add(restUserPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 330, 40));

        resetUserNewPassword.setBackground(new java.awt.Color(31, 36, 42));
        resetUserNewPassword.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        resetUserNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        resetUserNewPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49)));
        resetUserNewPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                resetUserNewPasswordMouseMoved(evt);
            }
        });
        jPanel6.add(resetUserNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 330, 40));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(169, 224, 49));
        //jLabel13.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_DOT_100px.png")); // NOI18N
        jLabel13.setText("Lahore General Hospital");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 310, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(169, 224, 49));
        jLabel12.setText("Management System");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 190, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(169, 224, 49));
        jLabel14.setText("User Name");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, 20));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(169, 224, 49));
        jLabel18.setText("New Password");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 314, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(169, 224, 49));
        jLabel16.setText("Phone");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 314, -1));

        jButton14.setBackground(new java.awt.Color(169, 224, 49));
        jButton14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(169, 224, 49));
        jButton14.setIcon(new javax.swing.ImageIcon("UIComponents\\icons8_Back_To_25px.png")); // NOI18N
        jButton14.setText("Back");
        jButton14.setBorder(null);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setRequestFocusEnabled(false);
        jButton14.setVerifyInputWhenFocusTarget(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 110, -1));

        resetButton.setBackground(new java.awt.Color(152, 201, 45));
        resetButton.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(21, 25, 28));
        resetButton.setText("Sign up");
        resetButton.setBorder(null);
        resetButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetButton.setFocusPainted(false);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel6.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 330, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 560));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 450, 620));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(169, 224, 49));
        jLabel20.setText("Password");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 70, -1));

        jButton7.setBackground(new java.awt.Color(152, 201, 45));
        jButton7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(21, 25, 28));
        jButton7.setText("Sign In");
        jButton7.setBorder(null);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginScreenButton(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void userNameMouseMoved(java.awt.event.MouseEvent evt) {

    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void resetUserNameMouseMoved(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void restUserPhoneMouseMoved(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void resetUserNewPasswordMouseMoved(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
        jPanel6.setVisible(false);
        jLabel_SoftZyd.setVisible(true);
        jLabel_inven.setVisible(true);
    }

    private void loginScreenButton(java.awt.event.ActionEvent evt) {
        System.out.println("this");
        // Button 1 action listerner (login)
        String userEmail=userName.getText();
        String userPass=userPassword.getText();
        boolean flag=modificationFunctions.searchEntities.searchLogin(userEmail,userPass);
        if(flag)
        {   ImageIcon icon=new ImageIcon("UIComponents\\tick.png");
            JOptionPane.showMessageDialog(null, "Successful Login","Done", JOptionPane.ERROR_MESSAGE,icon);
            this.setVisible(false);
            Welcome_Screen Welcome_frame=new Welcome_Screen();
            Welcome_frame.setVisible(true);
        }
        else
        {
            ImageIcon icon = new ImageIcon("UIComponents\\error.png");
            JOptionPane.showMessageDialog(null, "Login Failed!\nTry again please...", "Failed", JOptionPane.ERROR_MESSAGE, icon);
        }
    }

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String userEmail=resetUserName.getText();
        String userPhone=restUserPhone.getText();
        String userPassword=resetUserNewPassword.getText();
        boolean flag=false;
        try { flag= modificationFunctions.resetPassword(userEmail,userPhone,userPassword);} catch (IOException e) {}
        if(flag)
        {   ImageIcon icon=new ImageIcon("UIComponents\\good.png");
            JOptionPane.showMessageDialog(null, "Password Changed Successfully!","Done", JOptionPane.ERROR_MESSAGE,icon);
        }
        else {
            ImageIcon icon = new ImageIcon("UIComponents\\error.png");
            JOptionPane.showMessageDialog(null, "Invalid Username or Phone!","Failed",JOptionPane.ERROR_MESSAGE,icon);
        }
    }

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {
        this.setState(ICONIFIED);
        System.out.println("this");
    }

    private void forgotePasswordActionPerformed(java.awt.event.ActionEvent evt) {
        jLabel_SoftZyd.setVisible(false);
        jLabel_inven.setVisible(false);
        jPanel6.setVisible(true);
        //       jLabel7.setVisible(false);
        //       jLabel8.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton forgotePassword;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_SoftZyd;
    private javax.swing.JLabel jLabel_inven;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField resetUserName;
    private javax.swing.JTextField resetUserNewPassword;
    private javax.swing.JTextField restUserPhone;
    private javax.swing.JTextField userName;
    private javax.swing.JPasswordField userPassword;
    // End of variables declaration
}
