package com.Hospital.UIClasses;

import com.Hospital.Core_Classes.Patient;
import com.Hospital.SearchingAndModiciation_Classes.ModifyEntities;

import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class PatientsInWard_Screen extends javax.swing.JFrame{
    private final ModifyEntities modificationFunctions=new ModifyEntities();
    DefaultTableModel model;
    public PatientsInWard_Screen() {
        initComponents();
        model=(DefaultTableModel) showPatientTable.getModel();
        Image icon = Toolkit.getDefaultToolkit().getImage("UIComponents\\hos.png");
        this.setIconImage(icon);
        this.setTitle("Lahore General Hospital I.M.S");
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroupOPDAndEmergency = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ServiceLable = new javax.swing.JLabel();
        backToWellcomeScreen = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showPatientTable = new javax.swing.JTable();
        ViewOPDRadioButton = new javax.swing.JRadioButton();
        ViewEmergencyRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(171, 183, 183));
        jPanel2.setPreferredSize(new java.awt.Dimension(1609, 942));

        jLabel1.setIcon(new javax.swing.ImageIcon("UIComponents\\logo.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 130, 76));
        jLabel2.setText("Lahore General Hospital Management System");

        ServiceLable.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        ServiceLable.setForeground(new java.awt.Color(30, 130, 76));
        ServiceLable.setText(" ");


        backToWellcomeScreen.setBackground(new java.awt.Color(171, 183, 183));
        backToWellcomeScreen.setIcon(new javax.swing.ImageIcon("UIComponents\\back.png")); // NOI18N
        backToWellcomeScreen.setText("Back");
        backToWellcomeScreen.setToolTipText("Back to Wellcome Screen");
        backToWellcomeScreen.setBorder(null);
        backToWellcomeScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToWellcomeScreenActionPerformed(evt);
            }
        });

        showPatientTable.setAutoCreateRowSorter(true);
        showPatientTable.setBackground(new java.awt.Color(221, 221, 221));
        showPatientTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        showPatientTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "ID", "Name", "Service", "Age", "Gender", "COVID-19", "Phone", "C.N.I.C", "Address", "Admitted", "Entery Date"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showPatientTable.setToolTipText("Current Details of Patient");
        showPatientTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(showPatientTable);

        ViewOPDRadioButton.setBackground(new java.awt.Color(171, 183, 183));
        buttonGroupOPDAndEmergency.add(ViewOPDRadioButton);
        ViewOPDRadioButton.setText("OPD Patients");
        ViewOPDRadioButton.setBorder(null);
        ViewOPDRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOPDRadioButtonActionPerformed(evt);
            }
        });

        ViewEmergencyRadioButton.setBackground(new java.awt.Color(171, 183, 183));
        buttonGroupOPDAndEmergency.add(ViewEmergencyRadioButton);
        ViewEmergencyRadioButton.setText("Emergency Patients");
        ViewEmergencyRadioButton.setBorder(null);
        ViewEmergencyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmergencyRadioButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Clear Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(348, 348, 348)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(311, 311, 311)
                                                                .addComponent(backToWellcomeScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ViewOPDRadioButton)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jButton1))
                                                        .addComponent(ViewEmergencyRadioButton))
                                                .addGap(58, 58, 58)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ServiceLable, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(backToWellcomeScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ViewOPDRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ViewEmergencyRadioButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1)
                                                .addGap(303, 303, 303))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ServiceLable)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(22, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    //==================================================================================================================
    private void backToWellcomeScreenActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your Back to Wellcome here
        Welcome_Screen welcomeScreen=new Welcome_Screen();
        this.setVisible(false);
        welcomeScreen.setVisible(true);
    }
    //==================================================================================================================
    private void ViewOPDRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //opd patients
        List<Patient> patientList = modificationFunctions.searchEntities.getPatientList();
        model.setRowCount(0);
        ServiceLable.setText("Out-Patient Department");
        for(int count = 0; count< patientList.size(); count++)
        {
            if(patientList.get(count).getService().equals("OPD")) {
                model.addRow(new Object[]{patientList.get(count).getId(), patientList.get(count).getName(), patientList.get(count).getService(),
                        patientList.get(count).getAge(), patientList.get(count).getGender(), patientList.get(count).getCovid(), patientList.get(count).getPhone(),
                        patientList.get(count).getCnic(), patientList.get(count).getAddress(), patientList.get(count).getAdmitted(), patientList.get(count).getTime()});
            }
        }
    }
    //==================================================================================================================
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        model.setRowCount(0);
        ServiceLable.setText("-N/A-");
        buttonGroupOPDAndEmergency.clearSelection();
    }
    //==================================================================================================================
    private void ViewEmergencyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        //Emergency
        List<Patient> patientList = modificationFunctions.searchEntities.getPatientList();
        model.setRowCount(0);
        ServiceLable.setText("Emergency-Patient Department");
        for(int count = 0; count< patientList.size(); count++)
        {
            if(patientList.get(count).getService().equals("Emergency")) {
                model.addRow(new Object[]{patientList.get(count).getId(), patientList.get(count).getName(), patientList.get(count).getService(),
                        patientList.get(count).getAge(), patientList.get(count).getGender(), patientList.get(count).getCovid(), patientList.get(count).getPhone(),
                        patientList.get(count).getCnic(), patientList.get(count).getAddress(), patientList.get(count).getAdmitted(), patientList.get(count).getTime()});
            }
        }
    }
    //==================================================================================================================

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientsInWard_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientsInWard_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientsInWard_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientsInWard_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientsInWard_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel ServiceLable;
    private javax.swing.JRadioButton ViewEmergencyRadioButton;
    private javax.swing.JRadioButton ViewOPDRadioButton;
    private javax.swing.JToggleButton backToWellcomeScreen;
    private javax.swing.ButtonGroup buttonGroupOPDAndEmergency;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable showPatientTable;
    // End of variables declaration
}
